### ISSUE TITLE
CAN YOU PUT ALL FILES? PLS

### ISSUE THREAD

**Issue by DevTroxep** [mudithatharuka/Block_Buster#1]
PLEASE BRO CAN U PUT ALL FILES?

**Comment by mudithabatuwangala** [comment]
> PLEASE BRO CAN U PUT ALL FILES?

Sure, I'm still working on the main parts of this project. I'll push'em soon

**Comment by DevTroxep** [comment]
Thank you bro!

**Comment by DevTroxep** [comment]
Thank you bro! Do you have discord, if u have what is your name on it?

**Comment by mudithabatuwangala** [comment]
Still not bro, but I am in the thought of joining discord

**Comment by DevTroxep** [comment]
Ah okey bro, how can I contact you private?

**Comment by mudithabatuwangala** [comment]
Are you on Instagram bro?

**Comment by DevTroxep** [comment]
Eh i dont use instagram :(
Can you create a discord account soon?
When you create an account on the discord, can you leave here your discord tag(nickname)?
Thank you!

**Comment by mudithabatuwangala** [comment]
Sure, I'll put it here after I created one

**Comment by DevTroxep** [comment]
Okay bro, can you just upload inc/connection.php/functions.php and sql database? Thank anyways

**Comment by mudithabatuwangala** [comment]
> Okay bro, can you just upload inc/connection.php/functions.php and sql database? Thank anyways

functions.php file was added but the SQL file has been crashed.. I'll upload all of them soon. Sorry for the late bro

**Comment by DevTroxep** [comment]
Okey bro, thank you so much!
